services:
  grafana:
    image: grafana/grafana-oss:11.6.1
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASS}
      - GF_INSTALL_PLUGINS=grafana-pyroscope-app
      # disable analytics
      - GF_ANALYTICS_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - pyroscope
      - prometheus

  pyroscope:
    image: grafana/pyroscope:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:4040:4040
    volumes:
      - ./config/pyroscope/pyroscope.yaml:/etc/pyroscope/config.yaml

  prometheus:
    image: prom/prometheus:v3.3.0
    restart: unless-stopped
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  loki:
    image: grafana/loki:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:3100:3100
    volumes:
      - ./config/loki/loki.yaml://etc/loki/loki.yaml
    command: -config.file=/etc/loki/loki.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./config/promtail/promtail.yaml:/etc/promtail/promtail.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail.yml
    depends_on:
      - loki

  logging:
    build:
      context: ./cmd/logging
      dockerfile: Dockerfile
    labels:
      logging: "grafana"
    depends_on:
      - promtail

volumes:
  grafana-data:
  prometheus-data:
