# my global config
global:
  scrape_interval: 5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: test-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8001
